name: 'Run Tests'

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.next-php }}
    strategy:
      fail-fast: true
      matrix:
        php: [7.4]
        composer-flags: ['--prefer-stable']
        next-php: [false]
        extensions: ['curl, iconv, mbstring, mongodb, pdo, pdo_sqlite, sqlite, zip']
        include:
          - php: 7.4
            composer-flags: '--prefer-stable --prefer-lowest'
            next-php: false
            extensions: 'curl, iconv, mbstring, mongodb, pdo, pdo_sqlite, sqlite, zip'
          - php: 8.0
            composer-flags: '--prefer-stable --ignore-platform-req=php --ignore-platform-req=ext-mongodb'
            next-php: true
            extensions: 'curl, iconv, mbstring, pdo, pdo_sqlite, sqlite, zip'

    name: PHP ${{ matrix.php }} - Composer ${{ matrix.composer-flags }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}-flags-${{ matrix.composer-flags }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          extensions: ${{ matrix.extensions }}
          coverage: pcov

      - name: Install dependencies
        run: |
          composer require --dev --no-update doctrine/mongodb-odm:^2.0
          composer update ${{ matrix.composer-flags }} --prefer-dist

      - name: Execute tests
        run: vendor/bin/phpunit
